name: Create Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: bun run build